# Generated by Django 6.0.2 on 2026-02-04 07:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='video_file',
        ),
        migrations.AddField(
            model_name='video',
            name='youtube_url',
            field=models.URLField(default=django.utils.timezone.now, help_text='Paste the YouTube video link here'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='video',
            name='order',
            field=models.PositiveIntegerField(help_text='Lesson order: 1, 2, 3...'),
        ),
    ]
