# Generated by Django 6.0.2 on 2026-02-04 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_remove_video_video_file_video_youtube_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='current_lesson_index',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('student', 'course')},
        ),
    ]
