# Generated by Django 6.0.2 on 2026-02-04 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_enrollment_current_lesson_index_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='courses.video'),
        ),
    ]
