# Generated by Django 6.0.2 on 2026-02-04 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_quiz_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='course_interest',
            field=models.CharField(blank=True, help_text='What do you want to learn?', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='roll_no',
            field=models.CharField(blank=True, help_text='Your Student ID', max_length=20, null=True, unique=True),
        ),
    ]
