# Generated by Django 6.0.2 on 2026-02-04 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_user_age_user_course_interest_user_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='course_interest',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
