# Generated by Django 6.0.2 on 2026-02-04 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_user_course_interest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='course_interest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interested_students', to='courses.course'),
        ),
    ]
