# Generated by Django 6.0.2 on 2026-02-04 11:36

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_user_course_interest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='youtube_url',
        ),
        migrations.AddField(
            model_name='video',
            name='video_file',
            field=models.FileField(default=django.utils.timezone.now, help_text='Upload a video file (mp4, mov, avi, mkv)', upload_to='course_videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov', 'avi', 'mkv'])]),
            preserve_default=False,
        ),
    ]
