# Generated by Django 6.0.2 on 2026-02-06 05:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_enrollment_certificate_id_enrollment_completed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='study_material',
            field=models.FileField(blank=True, help_text='Upload a PDF resource for this lesson.', null=True, upload_to='materials/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
