# Generated by Django 6.0.2 on 2026-02-06 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_video_study_material'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='study_material',
        ),
        migrations.AddField(
            model_name='video',
            name='summary',
            field=models.TextField(blank=True, help_text='Enter key points for this lesson. These will be generated into a PDF.', null=True),
        ),
    ]
