# Generated by Django 6.0.2 on 2026-02-06 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_remove_video_study_material_video_summary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='summary',
        ),
        migrations.AddField(
            model_name='video',
            name='study_material',
            field=models.FileField(blank=True, help_text='Upload PDF notes for students', null=True, upload_to='materials/'),
        ),
    ]
