# Generated by Django 6.0.2 on 2026-03-02 16:12

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_comment_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('duration_minutes', models.PositiveIntegerField(help_text='Duration of the exam in minutes')),
                ('passing_percentage', models.PositiveIntegerField(default=50)),
                ('is_active', models.BooleanField(default=True, help_text='Toggle to enable/disable this exam')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='courses.course')),
            ],
        ),
        migrations.CreateModel(
            name='ExamQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('option_1', models.CharField(max_length=200)),
                ('option_2', models.CharField(max_length=200)),
                ('option_3', models.CharField(max_length=200)),
                ('option_4', models.CharField(max_length=200)),
                ('correct_option', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='courses.exam')),
            ],
        ),
        migrations.CreateModel(
            name='ExamSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('score', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ongoing', 'Ongoing'), ('submitted', 'Submitted'), ('flagged', 'Flagged for Review'), ('disqualified', 'Disqualified')], default='ongoing', max_length=20)),
                ('is_reviewed', models.BooleanField(default=False)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProctoringLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('violation_type', models.CharField(choices=[('no_face', 'Face Absence'), ('multi_face', 'Multiple Persons Detected'), ('gaze_deviation', 'Eye Gaze Deviation'), ('head_pose', 'Suspicious Head Movement'), ('tab_switch', 'Browser Tab Switch'), ('phone_detected', 'Mobile Phone Detected')], max_length=30)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('evidence_image', models.ImageField(blank=True, null=True, upload_to='proctoring_evidence/')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proctoring_logs', to='courses.examsession')),
            ],
        ),
    ]
