# Generated by Django 6.0.2 on 2026-03-02 17:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_exam_examquestion_examsession_proctoringlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examsession',
            name='exam',
        ),
        migrations.RemoveField(
            model_name='examquestion',
            name='exam',
        ),
        migrations.RemoveField(
            model_name='examsession',
            name='student',
        ),
        migrations.CreateModel(
            name='QuizSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('score', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ongoing', 'Ongoing'), ('submitted', 'Submitted'), ('flagged', 'Flagged for Review'), ('disqualified', 'Disqualified')], default='ongoing', max_length=20)),
                ('is_reviewed', models.BooleanField(default=False)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_sessions', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proctored_sessions', to='courses.video')),
            ],
        ),
        migrations.AlterField(
            model_name='proctoringlog',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proctoring_logs', to='courses.quizsession'),
        ),
        migrations.DeleteModel(
            name='Exam',
        ),
        migrations.DeleteModel(
            name='ExamQuestion',
        ),
        migrations.DeleteModel(
            name='ExamSession',
        ),
    ]
