# Generated by Django 6.0.2 on 2026-03-21 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_remove_examsession_exam_remove_examquestion_exam_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizsession',
            name='allow_retake',
            field=models.BooleanField(default=False),
        ),
    ]
