# Generated by Django 5.0.3 on 2026-04-19 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_user_is_examiner_alter_comment_id_alter_course_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizsession',
            name='allow_retake',
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, help_text='Short biography or professional summary', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='experience_years',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='specialty',
            field=models.CharField(blank=True, help_text='Expertise (e.g. Mathematics, AI, Math)', max_length=100, null=True),
        ),
    ]
