# Generated by Django 5.0.3 on 2026-04-19 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0021_remove_quizsession_allow_retake_user_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizsession',
            name='allow_retake',
            field=models.BooleanField(default=False),
        ),
    ]
