# Generated by Django 5.0.3 on 2026-04-19 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0024_alter_quizsession_video_exam_quizsession_exam_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examquestion',
            name='correct_option',
        ),
        migrations.AddField(
            model_name='examquestion',
            name='correct_answer',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='examquestion',
            name='points',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='examquestion',
            name='q_type',
            field=models.CharField(choices=[('mcq', 'Single Choice'), ('multi', 'Multiple Choice'), ('essay', 'Descriptive Essay')], default='mcq', max_length=20),
        ),
        migrations.AlterField(
            model_name='examquestion',
            name='option_1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='examquestion',
            name='option_2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='examquestion',
            name='option_3',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='examquestion',
            name='option_4',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='StudentAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_options', models.CharField(blank=True, max_length=50, null=True)),
                ('essay_text', models.TextField(blank=True, null=True)),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('marks_earned', models.FloatField(default=0.0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.examquestion')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='courses.quizsession')),
            ],
        ),
    ]
